### ISSUE TITLE
Change programming language to make your script useable

### ISSUE THREAD

**Issue by vusketta** [Irregulariti/help_me_please_laba1#1]
During the design of your project, you chose the _wrong_ programming language. Here are the following PLs, which meet the current quality standards in the world. 

- [x] Java
- [x] Kotlin
- [x] C++
- [x] Haskell

> code with Java, epta...

**Comment by Irregulariti** [comment]
ты кумир забыл...

**Comment by Irregulariti** [comment]
![Image alt](https://github.com/Irregulariti/help_me_please_laba1/raw/master/forreadme/absolute.png)
